PhamThiHongTham_2122110203/Controllers/BlankStarterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PhamThiHongTham_2122110203.Controllers
{
    public class BlankStarterController : Controller
    {
        // GET: BlankStarter
        public ActionResult BlankStarter()
        {
            return View();
        }
    }
}

PhamThiHongTham_2122110203/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PhamThiHongTham_2122110203.Controllers
{
    public class CategoryController : Controller
    {
        // GET: Category
        public ActionResult AllCategory()
        {
            return View();
        }
    }
}

PhamThiHongTham_2122110203/Controllers/ComponentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PhamThiHongTham_2122110203.Controllers
{
    public class ComponentsController : Controller
    {
        // GET: Components
        public ActionResult Components()
        {
            return View();
        }
    }
}

PhamThiHongTham_2122110203/Controllers/ContentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PhamThiHongTham_2122110203.Controllers
{
    public class ContentController : Controller
    {
        // GET: Content
        public ActionResult Content()
        {
            return View();
        }
    }
}

PhamThiHongTham_2122110203/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PhamThiHongTham_2122110203.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        
    }
}

PhamThiHongTham_2122110203/Controllers/ListingGridController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PhamThiHongTham_2122110203.Controllers
{
    public class ListingGridController : Controller
    {
        // GET: ListingGrid
        public ActionResult ListingGrid()
        {
            return View();
        }
    }
}

PhamThiHongTham_2122110203/Controllers/ListingLargeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PhamThiHongTham_2122110203.Controllers
{
    public class ListingLargeController : Controller
    {
        // GET: ListingLarge
        public ActionResult ListingLarge()
        {
            return View();
        }
    }
}

PhamThiHongTham_2122110203/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PhamThiHongTham_2122110203.Controllers
{
    public class ProductController : Controller
    {
        // GET: Product
        public ActionResult Detail()
        {
            return View();
        }
    }
}

PhamThiHongTham_2122110203/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PhamThiHongTham_2122110203.Controllers
{
    public class ShoppingCartController : Controller
    {
        // GET: ShoppingCart
        public ActionResult ShoppingCart
            ()
        {
            return View();
        }
    }
}

PhamThiHongTham_2122110203/Controllers/UserLoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PhamThiHongTham_2122110203.Controllers
{
    public class UserLoginController : Controller
    {
        // GET: UserLogin
        public ActionResult UserLogin()
        {
            return View();
        }
    }
}

PhamThiHongTham_2122110203/Controllers/UserRegisterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PhamThiHongTham_2122110203.Controllers
{
    public class UserRegisterController : Controller
    {
        // GET: UserRegister
        public ActionResult UserRegister()
        {
            return View();
        }
    }
}

PhamThiHongTham_2122110203/Views/BlankStarter/BlankStarter.cshtml
@{
    ViewBag.Title = "BlankStarter";

}


<section class="section-content padding-y">
    <div class="container">

        <header class="section-heading">
            <h2 class="section-title">Starter page </h2>
        </header><!-- sect-heading -->

        <article>


            <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
                cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
                proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
            </p>
            <p>
                Ut enim ad minim veniam,
                quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
                cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
                proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
            </p>
            <p>
                Ut enim ad minim veniam,
                quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
                cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
                proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
            </p>

            <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
                cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
                proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
            </p>
            <p>
                Ut enim ad minim veniam,
                quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
                cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
                proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
            </p>

            <br><br><br><br><br><br><br><br><br>

        </article>

    </div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

PhamThiHongTham_2122110203/Views/Category/AllCategory.cshtml
@{
    ViewBag.Title = "AllCategory";
}

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content padding-y">
    <div class="container">

        <nav class="row">
            <div class="col-md-3">

                <div class="card card-category">
                    <div class="img-wrap" style="background: #ffd7d7">
                        <img src="~/Content/images/items/1.jpg">
                    </div>
                    <div class="card-body">
                        <h4 class="card-title"><a href="#">Summer shirts</a></h4>
                        <ul class="list-menu">
                            <li><a href="">Unisex T shirts</a></li>
                            <li><a href="">Casual shirts</a></li>
                            <li><a href="">Scherf Ice cream</a></li>
                            <li><a href="">Another category</a></li>
                            <li><a href="">Great items name</a></li>
                            <li><a href="">Great items name</a></li>
                        </ul>
                    </div>
                </div>
            </div> <!-- col.// -->
            <div class="col-md-3">
                <div class="card card-category">
                    <div class="img-wrap" style="background: #FFF68D">
                        <img src="~/Content/images/items/2.jpg">
                    </div>
                    <div class="card-body">
                        <h4 class="card-title"><a href="#">Winter jackets</a></h4>
                        <ul class="list-menu">
                            <li><a href="">Leather jackets</a></li>
                            <li><a href="">Men's jackets</a></li>
                            <li><a href="">Heating battery clothes</a></li>
                            <li><a href="">Jeans jackets</a></li>
                            <li><a href="">Great items name</a></li>
                        </ul>
                    </div>
                </div>
            </div> <!-- col.// -->
            <div class="col-md-3">
                <div class="card card-category">
                    <div class="img-wrap" style="background: #bcffb8">
                        <img src="~/Content/images/items/3.jpg">
                    </div>
                    <div class="card-body">
                        <h4 class="card-title"><a href="#">Shorts</a></h4>
                        <ul class="list-menu">
                            <li><a href="">Jeans shorts</a></li>
                            <li><a href="">Swimming shorts</a></li>
                            <li><a href="">Another some shorts</a></li>
                            <li><a href="">Another category</a></li>
                        </ul>
                    </div>
                </div>
            </div> <!-- col.// -->
            <div class="col-md-3">
                <div class="card card-category">
                    <div class="img-wrap" style="background: #c9fff3">
                        <img src="~/Content/images/items/4.jpg">
                    </div>
                    <div class="card-body">
                        <h4 class="card-title"><a href="#">Travel bags </a></h4>
                        <ul class="list-menu">
                            <li><a href="">Leather bags</a></li>
                            <li><a href="">Cook & Hold ovens</a></li>
                            <li><a href="">Scherf Ice cream</a></li>
                            <li><a href="">Another category</a></li>
                            <li><a href="">Great items name</a></li>
                        </ul>
                    </div>
                </div>
            </div> <!-- col.// -->
            <div class="col-md-3">
                <div class="card card-category">
                    <a href="#" class="img-wrap" style="background: #ddffeb">
                        <img src="~/Content/images/items/5.jpg">
                    </a>
                    <div class="card-body">
                        <h4 class="card-title"><a href="#">Great items</a></h4>
                        <ul class="list-menu">
                            <li><a href="">Combi steamers</a></li>
                            <li><a href="">Cook & Hold ovens</a></li>
                            <li><a href="">Scherf Ice cream</a></li>
                            <li><a href="">Another category</a></li>
                            <li><a href="">Great items name</a></li>
                        </ul>
                    </div>
                </div>
            </div> <!-- col.// -->
            <div class="col-md-3">
                <div class="card card-category">
                    <a href="#" class="img-wrap" style="background: #dee4ff">
                        <img src="~/Content/images/items/6.jpg">
                    </a>
                    <div class="card-body">
                        <h4 class="card-title"><a href="#">Kitchen furniture</a></h4>
                        <ul class="list-menu">
                            <li><a href="">Combi steamers</a></li>
                            <li><a href="">Cook & Hold ovens</a></li>
                            <li><a href="">Scherf Ice cream</a></li>
                            <li><a href="">Another category</a></li>
                            <li><a href="">Great items name</a></li>
                        </ul>
                    </div>
                </div>
            </div> <!-- col.// -->
            <div class="col-md-3">
                <div class="card card-category">
                    <a href="#" class="img-wrap" style="background: #ddffeb">
                        <img src="~/Content/images/items/2.jpg">
                    </a>
                    <div class="card-body">
                        <h4 class="card-title"><a href="#">Great items</a></h4>
                        <ul class="list-menu">
                            <li><a href="">Combi steamers</a></li>
                            <li><a href="">Cook & Hold ovens</a></li>
                            <li><a href="">Scherf Ice cream</a></li>
                            <li><a href="">Another category</a></li>
                            <li><a href="">Great items name</a></li>
                        </ul>
                    </div>
                </div>
            </div> <!-- col.// -->
            <div class="col-md-3">
                <div class="card card-category">
                    <a href="#" class="img-wrap" style="background: #dee4ff">
                        <img src="~/Content/images/items/1.jpg">
                    </a>
                    <div class="card-body">
                        <h4 class="card-title"><a href="#">Other clothes</a></h4>
                        <ul class="list-menu">
                            <li><a href="">Jeans shorts</a></li>
                            <li><a href="">Cook & Hold ovens</a></li>
                            <li><a href="">Scherf Ice cream</a></li>
                            <li><a href="">Another category</a></li>
                            <li><a href="">Great items name</a></li>
                        </ul>
                    </div>
                </div>
            </div> <!-- col.// -->
        </nav> <!-- row.// -->


    </div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->
<!-- ========================= SECTION SUBSCRIBE  ========================= -->
<section class="padding-y-lg bg-light border-top">
    <div class="container">

        <p class="pb-2 text-center">Delivering the latest product trends and industry news straight to your inbox</p>

        <div class="row justify-content-md-center">
            <div class="col-lg-4 col-sm-6">
                <form class="form-row">
                    <div class="col-8">
                        <input class="form-control" placeholder="Your Email" type="email">
                    </div> <!-- col.// -->
                    <div class="col-4">
                        <button type="submit" class="btn btn-block btn-warning"> <i class="fa fa-envelope"></i> Subscribe </button>
                    </div> <!-- col.// -->
                </form>
                <small class="form-text">We’ll never share your email address with a third-party. </small>
            </div> <!-- col-md-6.// -->
        </div>


    </div>
</section>
<!-- ========================= SECTION SUBSCRIBE END// ========================= -->

PhamThiHongTham_2122110203/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

PhamThiHongTham_2122110203/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

PhamThiHongTham_2122110203/Views/Shared/_Layout.cshtml
<!DOCTYPE HTML>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="pragma" content="no-cache" />
    <meta http-equiv="cache-control" content="max-age=604800" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Website title - bootstrap html template</title>

    <link href="~/Content/images/favicon.ico" rel="shortcut icon" type="image/x-icon">

    <!-- jQuery -->
    <script src="~/Content/js/jquery-2.0.0.min.js" type="text/javascript"></script>

    <!-- Bootstrap4 files-->
    <script src="~/Content/js/bootstrap.bundle.min.js" type="text/javascript"></script>
    <link href="~/Content/css/bootstrap.css" rel="stylesheet" type="text/css" />

    <!-- Font awesome 5 -->
    <link href="~/Content/fonts/fontawesome/css/all.min.css" type="text/css" rel="stylesheet">

    <!-- custom style -->
    <link href="~/Content/css/ui.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/css/responsive.css" rel="stylesheet" type="text/css" />
    <!-- custom javascript -->
    <script src="~/Content/js/script.js" type="text/javascript"></script>

</head>
<body>

    <header class="section-header">
        <section class="header-main border-bottom">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-xl-2 col-lg-3 col-md-12">
                        <a href="http://bootstrap-ecommerce.com" class="brand-wrap">
                            <img class="logo" src="~/Content/images/logo.png">
                        </a> <!-- brand-wrap.// -->
                    </div>
                    <div class="col-xl-6 col-lg-5 col-md-6">
                        <form action="#" class="search-header">
                            <div class="input-group w-100">
                                <select class="custom-select border-right" name="category_name">
                                    <option value="">All type</option>
                                    <option value="codex">Special</option>
                                    <option value="comments">Only best</option>
                                    <option value="content">Latest</option>
                                </select>
                                <input type="text" class="form-control" placeholder="Search">

                                <div class="input-group-append">
                                    <button class="btn btn-primary" type="submit">
                                        <i class="fa fa-search"></i> Search
                                    </button>
                                </div>
                            </div>
                        </form> <!-- search-wrap .end// -->
                    </div> <!-- col.// -->
                    <div class="col-xl-4 col-lg-4 col-md-6">
                        <div class="widgets-wrap float-md-right">
                            <div class="widget-header mr-3">
                                <a href="#" class="widget-view">
                                    <div class="icon-area">
                                        <i class="fa fa-user"></i>
                                        <span class="notify">3</span>
                                    </div>
                                    <small class="text"> My profile </small>
                                </a>
                            </div>
                            <div class="widget-header mr-3">
                                <a href="#" class="widget-view">
                                    <div class="icon-area">
                                        <i class="fa fa-comment-dots"></i>
                                        <span class="notify">1</span>
                                    </div>
                                    <small class="text"> Message </small>
                                </a>
                            </div>
                            <div class="widget-header mr-3">
                                <a href="#" class="widget-view">
                                    <div class="icon-area">
                                        <i class="fa fa-store"></i>
                                    </div>
                                    <small class="text"> Orders </small>
                                </a>
                            </div>
                            <div class="widget-header">
                                <a href="#" class="widget-view">
                                    <div class="icon-area">
                                        <i class="fa fa-shopping-cart"></i>
                                    </div>

                                    @Html.ActionLink("Cart ", "ShoppingCart", "ShoppingCart", new { }, new { @class = "text" })
                                </a>
                            </div>
                        </div> <!-- widgets-wrap.// -->
                    </div> <!-- col.// -->
                </div> <!-- row.// -->
            </div> <!-- container.// -->
        </section> <!-- header-main .// -->


        <nav class="navbar navbar-main navbar-expand-lg border-bottom">
            <div class="container">

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main_nav" aria-controls="main_nav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="main_nav">
                    <ul class="navbar-nav">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#">
                                <i class="fa fa-bars text-muted mr-2"></i> Categories
                            </a>
                            <div class="dropdown-menu">
                                @Html.ActionLink("Machinery", "AllCategory", "Category", new { categoryName = "Machinery" }, new { @class = "dropdown-item" })
                                @Html.ActionLink("Electronics", "AllCategory", "Category", new { categoryName = "Electronics" }, new { @class = "dropdown-item" })
                                @Html.ActionLink("Home textile", "AllCategory", "Category", new { categoryName = "HomeTextile" }, new { @class = "dropdown-item" })
                                @Html.ActionLink("Home and kitchen", "AllCategory", "Category", new { categoryName = "HomeKitchen" }, new { @class = "dropdown-item" })
                                @Html.ActionLink("Service and equipment", "AllCategory", "Category", new { categoryName = "ServiceEquipment" }, new { @class = "dropdown-item" })
                                @Html.ActionLink("Healthcare items", "AllCategory", "Category", new { categoryName = "Healthcare" }, new { @class = "dropdown-item" })
                                @Html.ActionLink("Toys and Hobbies", "AllCategory", "Category", new { categoryName = "ToysHobbies" }, new { @class = "dropdown-item" })
                            </div>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="#">Ready to ship</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Trade shows</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Services</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Sell with us</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#">Demo pages</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="page-index.html">Main</a>
                                @Html.ActionLink("All category", "AllCategory", "Category", new { page = "category" }, new { @class = "dropdown-item" })
                                @Html.ActionLink("Listing list", "ListingLarge", "ListingLarge", new { page = "listing-large" }, new { @class = "dropdown-item" })
                                @Html.ActionLink("Listing grid", "ListingGrid", "ListingGrid", new { page = "listing-grid" }, new { @class = "dropdown-item" })
                                @Html.ActionLink("Shopping cart", "ShoppingCart", "ShoppingCart", new { page = "shopping-cart" }, new { @class = "dropdown-item" })
                                @Html.ActionLink("Item detail", "Detail", "Product", new { page = "detail-product" }, new { @class = "dropdown-item" })
                                @Html.ActionLink("Info content", "Content", "Content", new { page = "content" }, new { @class = "dropdown-item" })
                                @Html.ActionLink("Page login", "UserLogin", "UserLogin", new { page = "user-login" }, new { @class = "dropdown-item" })
                                @Html.ActionLink("Page register", "UserRegister", "UserRegister", new { page = "user-register" }, new { @class = "dropdown-item" })
                                <a class="dropdown-item disabled text-muted" href="#">More components</a>
                            </div>
                        </li>
                    </ul>
                    <ul class="navbar-nav ml-md-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="#">Get the app</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="http://example.com" data-toggle="dropdown">English</a>
                            <div class="dropdown-menu dropdown-menu-right">
                                <a class="dropdown-item" href="#">Russian</a>
                                <a class="dropdown-item" href="#">French</a>
                                <a class="dropdown-item" href="#">Spanish</a>
                                <a class="dropdown-item" href="#">Chinese</a>
                            </div>
                        </li>
                    </ul>
                </div> <!-- collapse .// -->
            </div> <!-- container .// -->
        </nav>
    </header> <!-- section-header.// -->


    @RenderBody()



    <!-- ========================= FOOTER ========================= -->
    <footer class="section-footer bg-secondary">
        <div class="container">
            <section class="footer-top padding-y-lg text-white">
                <div class="row">
                    <aside class="col-md col-6">
                        <h6 class="title">Brands</h6>
                        <ul class="list-unstyled">
                            <li> <a href="#">Adidas</a></li>
                            <li> <a href="#">Puma</a></li>
                            <li> <a href="#">Reebok</a></li>
                            <li> <a href="#">Nike</a></li>
                        </ul>
                    </aside>
                    <aside class="col-md col-6">
                        <h6 class="title">Company</h6>
                        <ul class="list-unstyled">
                            <li> <a href="#">About us</a></li>
                            <li> <a href="#">Career</a></li>
                            <li> <a href="#">Find a store</a></li>
                            <li> <a href="#">Rules and terms</a></li>
                            <li> <a href="#">Sitemap</a></li>
                        </ul>
                    </aside>
                    <aside class="col-md col-6">
                        <h6 class="title">Help</h6>
                        <ul class="list-unstyled">
                            <li> <a href="#">Contact us</a></li>
                            <li> <a href="#">Money refund</a></li>
                            <li> <a href="#">Order status</a></li>
                            <li> <a href="#">Shipping info</a></li>
                            <li> <a href="#">Open dispute</a></li>
                        </ul>
                    </aside>
                    <aside class="col-md col-6">
                        <h6 class="title">Account</h6>
                        <ul class="list-unstyled">
                            <li> <a href="#"> User Login </a></li>
                            <li> <a href="#"> User register </a></li>
                            <li> <a href="#"> Account Setting </a></li>
                            <li> <a href="#"> My Orders </a></li>
                        </ul>
                    </aside>
                    <aside class="col-md">
                        <h6 class="title">Social</h6>
                        <ul class="list-unstyled">
                            <li><a href="#"> <i class="fab fa-facebook"></i> Facebook </a></li>
                            <li><a href="#"> <i class="fab fa-twitter"></i> Twitter </a></li>
                            <li><a href="#"> <i class="fab fa-instagram"></i> Instagram </a></li>
                            <li><a href="#"> <i class="fab fa-youtube"></i> Youtube </a></li>
                        </ul>
                    </aside>
                </div> <!-- row.// -->
            </section>	<!-- footer-top.// -->

            <section class="footer-bottom text-center">

                <p class="text-white">Privacy Policy - Terms of Use - User Information Legal Enquiry Guide</p>
                <p class="text-muted"> &copy 2019 Company name, All rights reserved </p>
                <br>
            </section>
        </div><!-- //container -->
    </footer>
    <!-- ========================= FOOTER END // ========================= -->



</body>
</html>